var billApp = angular.module('billApp', ['ngRoute']);

/* CUSTOM DELIMITER NOTATION FOR ANGULAR FROM STACKOVERFLOW */
/* NOTE: See Credits Page for more detail */
/* TODO: Credits Page */
billApp.config(['$interpolateProvider', function($interpolateProvider) {
  $interpolateProvider.startSymbol('{a');
  $interpolateProvider.endSymbol('a}');
}]);

billApp.config(function($routeProvider) {
    $routeProvider.
    when('/', {
        templateUrl: 'temp/index-temp.html',
        controller: 'IndexCtrl'
    }).
    when('/newbill', {
        templateUrl: 'temp/newbill-temp.html', //either load temp here or in main.py
        controller: 'NewBillCtrl'
    }).
    when('/update', {
        templateUrl: 'temp/update-temp.html',
        controller: 'UpdateCtrl'
    }).
    when('/bills', { //TODO: will send an array to the temp from main.py (Datastore)
        templateUrl: 'temp/bills-temp.html',
        controller: 'BillsListCtrl'
    }).
    when('/success', {
        templateUrl: 'temp/success-temp.html',
        controller: 'SuccessCtrl'
    }).
    when('/bills/:billID', { //TODO: billId will be generated by main.py, maybe from Datastore keys
        templateUrl: 'temp/bill-temp.html',
        controller: 'BillDetailCtrl'
    }).
    otherwise({
        redirectTo: '/'
    });
});

/*

TODO: PUT FACTORIES HERE

*/

billApp.controller('IndexCtrl', function($scope, $routeParams, $http) {
    //TODO: run a class in main.py
});

billApp.controller('NewBillCtrl', function($scope, $routeParams, $http) {
    $scope.billSubmit = function() {
        console.log("Form function ran!");
        $http.post('/newBill').then(
            function() {
                console.log("Success!")
                window.location.assign("#/success");
            },
            function() {
                console.log("Failure!")
            });
    }
});

billApp.controller('UpdateCtrl', function($scope, $routeParams, $http) {
    //TODO: run a class in main.py
});

// billApp.controller('SuccessCtrl', function($scope, $routeParams, $http) {
//     // $http.get('/newBill');
// });

billApp.controller('BillsListCtrl', function($scope /*TODO: ARRAY HERE */) {
    // states.list(function(states) {
    //     $scope.states = states;
    // });
});

billApp.controller('BillDetailCtrl', function($scope, $routeParams /*TODO: ARRAY HERE */) {
    // states.find($routeParams.stateAbrv, function(state) {
    //     $scope.state = state;
    // });
    // reps.list(function(reps) {
    //     $scope.reps = reps;
    // });
});

//---- FILTERS ----//

billApp.filter('encodeURI', function() {
    return function(x) {
        return encodeURIComponent(x);
    };
});

// billApp.filter('repeat', function() {
//     return function(x) {
//         return x.split("ly", 1);
//     }
// });

// $http({method: 'POST', url: '/newBill', data: my_data}).
//     success(function(data, status, headers, config) {
//         // this callback will be called asynchronously
//         // when the response is available
//     }).
//     error(function(data, status, headers, config) {
//         // called asynchronously if an error occurs
//         // or server returns response with an error status.
//     });

// $http.get('/newBill');
